diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('diary/create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary/create/complete/', views.DiaryCreateCompleteView.as_view(), name='diary_create_complete'),
    path('diary/list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary/detail/<uuid:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),
    path('diary/update/<uuid:pk>/', views.DiaryUpdateView.as_view(), name='diary_update'),
    path('diary/delete/<uuid:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

mydiaryproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('account/', include('allauth.urls')),
]

accounts/models.py
from django.contrib.auth.models import UserManager, AbstractUser

class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, username, password, **extra_fields):
        # create_user と create_superuser の共通処理
        if not email:
            raise ValueError('email must be set')
        if not username:
            raise ValueError('username must be set')

        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, username, email=None, password=None, **extra_fields):

        if not email:
            raise ValueError('email must be set')
        if not username:
            raise ValueError('username must be set')

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, username, password, **extra_fields)
    
class CustomUser(AbstractUser):
    objects = CustomUserManager()

    def __str__(self):
        return self.email

diary/models.py
from django.db import models
from django.utils import timezone
import uuid


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(verbose_name='日付', default=timezone.now)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    text = models.CharField(verbose_name='本文', max_length=200)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

diary/forms.py
from django import forms
from .models import Diary


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('date', 'title', 'text',)
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
from django.views.generic import TemplateView, CreateView ,ListView ,DetailView , UpdateView ,DeleteView
from django.urls import reverse_lazy
from .forms import DiaryForm
from .models import Diary
from django.utils import timezone

class IndexView(TemplateView):
    template_name = 'index.html'

class DiaryCreateView(CreateView):
    template_name = 'diary_create.html'
    form_class = DiaryForm
    success_url = reverse_lazy('diary:diary_create_complete')

class DiaryCreateCompleteView(TemplateView):
    template_name = 'diary_create_complete.html'

class DiaryListView(ListView):
    template_name = 'diary_list.html'
    model = Diary

class DiaryDetailView(DetailView):
    template_name = 'diary_detail.html'
    model = Diary

class DiaryUpdateView(UpdateView):
    template_name = 'diary_update.html'
    model = Diary
    fields = ('date', 'title', 'text',)
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.updated_at = timezone.now()
        diary.save()
        return super().form_valid(form)

class DiaryDeleteView(DeleteView):
    template_name = 'diary_delete.html'
    model = Diary
    success_url = reverse_lazy('diary:diary_list')

templates/base.html
<!DOCTYPE html>
<html lang="jp">
{% bootstrap_css %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>e-Nikki</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light custom-navbar">
        <img src="{% static 'images/image.jpg' %}" alt="Logo" class="navbar-logo">
        <a class="navbar-brand" href="{% url 'diary:index' %}" style="font-family: 'Comic Sans MS', cursive; font-size: 24px; color: white;">e-Nikki</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="/registration">登録情報</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'account_logout' %}">ログアウト</a>
                </li>
            </ul>
        </div>
    </nav>    

    <div class="container">
            {% block content %}
            {% endblock %}
    </div>
</body>
</html>

templates/diary_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1>日記の作成</h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>{{ form.date.label }}</label>
                    {{ form.date | add_class:'form-control' }}
                </div>
                <div class="form-group">
                    <label>{{ form.title.label }}</label>
                    {{ form.title | add_class:'form-control' }}
                </div>
                <div class="form-group">
                    <label>{{ form.text.label }}</label>
                    {{ form.text | add_class:'form-control' }}
                </div>
                <button type="submit" class="btn btn-primary">投稿</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/diary_create_complete.html
{% extends 'base.html' %}
{% block content %}
<body>
<p>日記の投稿が完了しました！</p>
<a href="{% url 'diary:index' %}">トップへ戻る</a>
{% endblock %}

templates/diary_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>日記の削除</h1>
<form method="post">
    {% csrf_token %}
    <p>{{ diary.date }} {{ diary.title }} を削除します</p>
    <input type="submit" value="削除">
</form>
{% endblock %}

templates/diary_detail.html
{% extends 'base.html' %}
{% block content %}
<p>{{ diary.date }}</p>
<p>{{ diary.title }}</p>
<p>{{ diary.text }}</p>
<a href="{% url 'diary:diary_update' diary.pk %}">編集</a>
<a href="{% url 'diary:diary_delete' diary.pk %}">削除</a>
<a href="{% url 'diary:index' %}">戻る</a>
{% endblock %}

templates/diary_list.html
{% extends 'base.html' %}
{% block content %}
{% for diary in diary_list %}
<p>
    {{ diary.date }}
    <a href="{% url 'diary:diary_detail' diary.pk %}">{{ diary.title }}</a>
</p>
{% endfor %}
<a href="{% url 'diary:index' %}">戻る</a>
{% endblock %}

templates/diary_update.html
{% extends 'base.html' %}
{% block content %}
<h1>日記の編集</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container-fluid mt-5">
    <div class="image-container">
        <img src="{% static 'images/image.jpg' %}" class="img-fluid" alt="Header Image">
    </div>
    <h1 class="display-6 text-center e-Nikki">e-Nikki</h1>
    <hr class="my-4">
    <h2 class="display-6 text-center subtitle">あなたの素晴らしい日常の記録を残しませんか？</h2>
    <h4 class="display-6 text-center maintext">e-Nikkiは日々の記録を画像で残す</h4>
    <div class="row justify-content-center">
        <div class="col-md-6 mb-4">
            <div class="card mb-3 range rounded">
                <div class="card-body text-center">
                    <h5 class="card-title">日記の投稿</h5>
                    <br><br><br>
                    <a href="{% url 'diary:diary_create' %}" class="btn btn-success">新規作成</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6 mb-4">
            <div class="card mb-3 range rounded">
                <div class="card-body text-center">
                    <h5 class="card-title">日記の一覧</h5>
                    <br><br><br>
                    <a href="{% url 'diary:diary_list' %}" class="btn btn-success">過去の日記</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}